version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: social_media
      POSTGRES_PASSWORD: 1

    ports:
    - 1234:5432
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql